FROM almalinux:9
# ENV tool="docker" \
#     author="venkat"
# RUN echo "Hello ${author}" >/tmp/devops.txt
# ARG USERNAME="KIYANSH"
# RUN echo "Hello user: ${USERNAME}"
ARG USERNAME=JENNY
ENV Desired_Username=$USERNAME
CMD ["sleep", "1000"]